name: s1rtc
channels:
    - conda-forge
    - nodefaults  # force everything to come from conda-forge channel
dependencies:
    # - pip>=21.3  # https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#editable-installation
    - isce3=0.13.0  # Fix at v0.13.0 because that API matches RTC v0.4
    - lxml
    - numpy=1.24.3
    - pip:
        - git+https://github.com/opera-adt/s1-reader.git
        - git+https://github.com/opera-adt/RTC.git@v0.4
    - gdal>=3.4.2  # for s1reader. Must be >=3.4.2 for sardem
    - packaging  # from s1reader
    - requests  # from s1reader
    - shapely  # from s1reader
    - sentineleof>=0.9.1  # to download the Sentinel-1 Orbit files
    - sardem  # to download and crop the Copernicus DEM
    - maap

